import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/auth';

const DEEPSEEK_API_KEY = process.env.DEEPSEEK_API_KEY;
const DEEPSEEK_API_URL = 'https://api.deepseek.com/v1/chat/completions';

export async function POST(request: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { infrastructureBrief, technicalBrief, buildings } = body;

    if (!infrastructureBrief && !technicalBrief) {
      return NextResponse.json(
        { error: 'At least one brief description is required' },
        { status: 400 }
      );
    }

    // Build infrastructure context from buildings
    let infrastructureContext = '';
    if (buildings && buildings.length > 0) {
      infrastructureContext = buildings.map((b: any) => {
        const floorsCount = b.floors?.length || 0;
        const roomsCount = b.floors?.reduce((sum: number, f: any) => sum + (f.rooms?.length || 0), 0) || 0;
        return `Κτίριο: ${b.name}, ${floorsCount} όροφοι, ${roomsCount} χώροι`;
      }).join('; ');
    }

    // Construct AI prompt
    const prompt = `Είσαι τεχνικός σύμβουλος τηλεπικοινωνιών και δικτύων. Δημιούργησε μια επαγγελματική τεχνική περιγραφή για οικονομοτεχνική προσφορά.

ΠΛΗΡΟΦΟΡΙΕΣ ΕΡΓΟΥ:
${infrastructureBrief ? `\nΥποδομή: ${infrastructureBrief}` : ''}
${technicalBrief ? `\nΤεχνικές Απαιτήσεις: ${technicalBrief}` : ''}
${infrastructureContext ? `\nΔομή Κτιρίων: ${infrastructureContext}` : ''}

ΟΔΗΓΙΕΣ:
- Γράψε μια πλήρη τεχνική περιγραφή 800-1200 λέξεων
- Χρησιμοποίησε επαγγελματική γλώσσα
- Περίγραψε την υφιστάμενη κατάσταση και τα προβλήματα
- Εξήγησε την προτεινόμενη λύση και τα οφέλη
- Αναφέρου σε τεχνικές λεπτομέρειες (VoIP, IP PBX, δομημένη καλωδίωση, switches, κ.λπ.)
- Χρησιμοποίησε Ελληνικά κεφαλαία χωρίς τόνους για τίτλους (π.χ. ΤΕΧΝΙΚΗ ΠΕΡΙΓΡΑΦΗ)
- ΜΗΝ προσθέσεις τίτλο - μόνο το κείμενο της περιγραφής

Γράψε ΜΟΝΟ την τεχνική περιγραφή σε Ελληνικά:`;

    console.log('🤖 Calling DeepSeek API for technical description...');

    const aiResponse = await fetch(DEEPSEEK_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${DEEPSEEK_API_KEY}`,
      },
      body: JSON.stringify({
        model: 'deepseek-chat',
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        temperature: 0.7,
        max_tokens: 2000,
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('DeepSeek API error:', errorText);
      throw new Error('Failed to generate AI description');
    }

    const aiData = await aiResponse.json();
    const technicalDescription = aiData.choices?.[0]?.message?.content || '';

    if (!technicalDescription) {
      throw new Error('No content generated by AI');
    }

    console.log('✅ AI technical description generated successfully');

    return NextResponse.json({
      success: true,
      technicalDescription,
    });

  } catch (error: any) {
    console.error('❌ Error generating AI technical description:', error);
    return NextResponse.json(
      {
        error: 'Failed to generate AI technical description',
        details: error.message,
      },
      { status: 500 }
    );
  }
}

